create table public.users (
  id uuid not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  avatar_url text null,
  deleted_at timestamp with time zone null,
  email character varying(255) not null,
  enabled boolean not null,
  name character varying(255) not null,
  password_hash character varying(255) not null,
  phone character varying(20) null,
  provider character varying(50) null,
  role character varying(20) not null,
  constraint users_pkey primary key (id),
  constraint uk6dotkott2kjsp8vw4d0m25fb7 unique (email),
  constraint users_role_check check (
    (
      (role)::text = any (
        (
          array[
            'USER'::character varying,
            'ADMIN'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_users_email on public.users using btree (email) TABLESPACE pg_default;

create index IF not exists idx_users_role on public.users using btree (role) TABLESPACE pg_default;

create index IF not exists idx_users_enabled on public.users using btree (enabled) TABLESPACE pg_default;

create table public.brands (
  id bigint generated by default as identity not null,
  name character varying(100) not null,
  constraint brands_pkey primary key (id),
  constraint ukoce3937d2f4mpfqrycbr0l93m unique (name)
) TABLESPACE pg_default;

create table public.categories (
  id bigint generated by default as identity not null,
  active boolean not null,
  created_at timestamp with time zone not null,
  description text null,
  image_url character varying(500) null,
  name character varying(255) not null,
  updated_at timestamp with time zone not null,
  constraint categories_pkey primary key (id),
  constraint ukt8o6pivur7nn124jehx7cygw5 unique (name)
) TABLESPACE pg_default;

create index IF not exists idx_categories_name on public.categories using btree (name) TABLESPACE pg_default;

create table public.products (
  id uuid not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  active boolean not null,
  deleted_at timestamp with time zone null,
  listed_price numeric(12, 2) not null,
  long_desc text null,
  name character varying(255) not null,
  price numeric(12, 2) not null,
  rating double precision not null,
  review_count integer not null,
  short_desc text null,
  sku character varying(100) not null,
  thumbnail_url character varying(2048) null,
  brand_id bigint null,
  category_id bigint null,
  constraint products_pkey primary key (id),
  constraint ukfhmd06dsmj6k0n90swsh8ie9g unique (sku),
  constraint fka3a4mpsfdf4d2y6r8ra3sc8mv foreign KEY (brand_id) references brands (id),
  constraint fkog2rp4qthbtt2lfyhfo32lsw9 foreign KEY (category_id) references categories (id),
  constraint products_review_count_check check ((review_count >= 0))
) TABLESPACE pg_default;

create index IF not exists idx_products_sku on public.products using btree (sku) TABLESPACE pg_default;

create index IF not exists idx_products_active on public.products using btree (active) TABLESPACE pg_default;

create index IF not exists idx_products_category on public.products using btree (category_id) TABLESPACE pg_default;

create index IF not exists idx_products_brand on public.products using btree (brand_id) TABLESPACE pg_default;

create index IF not exists idx_products_name on public.products using btree (name) TABLESPACE pg_default;

create index IF not exists idx_products_listed_price on public.products using btree (listed_price) TABLESPACE pg_default;

create index IF not exists idx_products_price on public.products using btree (price) TABLESPACE pg_default;

create table public.media_assets (
  id bigint generated by default as identity not null,
  alt_text character varying(255) null,
  url character varying(2048) not null,
  product_id uuid not null,
  constraint media_assets_pkey primary key (id),
  constraint fkeyspdi4nak3mepn9up0k3vb6j foreign KEY (product_id) references products (id)
) TABLESPACE pg_default;

create table public.inventory (
  id bigint generated by default as identity not null,
  on_hand integer not null,
  reserved integer not null,
  product_id uuid not null,
  constraint inventory_pkey primary key (id),
  constraint ukce3rbi3bfstbvvyne34c1dvyv unique (product_id),
  constraint fkq2yge7ebtfuvwufr6lwfwqy9l foreign KEY (product_id) references products (id),
  constraint inventory_on_hand_check check ((on_hand >= 0)),
  constraint inventory_reserved_check check ((reserved >= 0))
) TABLESPACE pg_default;


create table public.discounts (
  id uuid not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  active boolean not null,
  code character varying(50) not null,
  discount_type character varying(50) not null,
  discount_value numeric(15, 2) not null,
  end_at timestamp with time zone not null,
  max_usage integer null,
  min_order_value numeric(15, 2) null,
  per_user_limit integer null,
  start_at timestamp with time zone not null,
  used integer null,
  constraint discounts_pkey primary key (id),
  constraint ukbc29q3wh0lqhy0k84bx3afk08 unique (code),
  constraint discounts_discount_type_check check (
    (
      (discount_type)::text = any (
        (
          array[
            'PERCENT'::character varying,
            'FIXED_AMOUNT'::character varying,
            'FREE_SHIP'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint discounts_per_user_limit_check check ((per_user_limit >= 1))
) TABLESPACE pg_default;

create index IF not exists idx_discounts_code on public.discounts using btree (code) TABLESPACE pg_default;

create index IF not exists idx_discounts_active on public.discounts using btree (active) TABLESPACE pg_default;

create index IF not exists idx_discounts_dates on public.discounts using btree (start_at, end_at) TABLESPACE pg_default;


create table public.addresses (
  id bigint generated by default as identity not null,
  is_default boolean not null,
  name character varying(100) not null,
  phone character varying(20) not null,
  province character varying(100) not null,
  street character varying(255) not null,
  ward character varying(100) not null,
  user_id uuid not null,
  constraint addresses_pkey primary key (id),
  constraint fk1fa36y2oqhao3wgg2rw1pi459 foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;

create table public.orders (
  id uuid not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  cancelled_at timestamp with time zone null,
  confirmed_at timestamp with time zone null,
  discount_total numeric(15, 2) not null,
  grand_total numeric(15, 2) not null,
  has_paid boolean not null,
  payment_status character varying(50) not null,
  shipping_address jsonb not null,
  shipping_fee numeric(15, 2) not null,
  status character varying(50) not null,
  sub_total numeric(15, 2) not null,
  discount_id uuid null,
  user_id uuid not null,
  constraint orders_pkey primary key (id),
  constraint fk32ql8ubntj5uh44ph9659tiih foreign KEY (user_id) references users (id),
  constraint fksxfvku34v9ujavmj9ao69vo8s foreign KEY (discount_id) references discounts (id),
  constraint orders_payment_status_check check (
    (
      (payment_status)::text = any (
        (
          array[
            'UNPAID'::character varying,
            'PAID'::character varying,
            'FAILED'::character varying,
            'REFUNDED'::character varying,
            'PENDING'::character varying,
            'PROCESSING'::character varying,
            'PARTIAL_REFUND'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint orders_status_check check (
    (
      (status)::text = any (
        (
          array[
            'PENDING'::character varying,
            'WAITING_FOR_DELIVERY'::character varying,
            'IN_TRANSIT'::character varying,
            'DELIVERED'::character varying,
            'CONFIRMED'::character varying,
            'CANCELLED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_orders_user on public.orders using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_orders_status on public.orders using btree (status) TABLESPACE pg_default;

create index IF not exists idx_orders_payment_status on public.orders using btree (payment_status) TABLESPACE pg_default;

create index IF not exists idx_orders_created_at on public.orders using btree (created_at) TABLESPACE pg_default;


create table public.order_items (
  id bigint generated by default as identity not null,
  line_total numeric(15, 2) not null,
  quantity integer not null,
  unit_price numeric(15, 2) not null,
  order_id uuid not null,
  product_id uuid not null,
  constraint order_items_pkey primary key (id),
  constraint uk_order_product unique (order_id, product_id),
  constraint fkbioxgbv59vetrxe0ejfubep1w foreign KEY (order_id) references orders (id),
  constraint fkocimc7dtr037rh4ls4l95nlfi foreign KEY (product_id) references products (id)
) TABLESPACE pg_default;

create index IF not exists idx_order_items_order on public.order_items using btree (order_id) TABLESPACE pg_default;

create index IF not exists idx_order_items_product on public.order_items using btree (product_id) TABLESPACE pg_default;

create table public.payments (
  id uuid not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  amount numeric(15, 2) not null,
  gateway_response jsonb null,
  method character varying(50) not null,
  paid_at timestamp with time zone null,
  provider character varying(50) not null,
  status character varying(50) not null,
  transaction_id character varying(255) null,
  order_id uuid not null,
  constraint payments_pkey primary key (id),
  constraint uk8vo36cen604as7etdfwmyjsxt unique (order_id),
  constraint fk81gagumt0r8y3rmudcgpbk42l foreign KEY (order_id) references orders (id),
  constraint payments_method_check check (
    (
      (method)::text = any (
        (
          array[
            'COD'::character varying,
            'BANK_TRANSFER'::character varying,
            'E_WALLET'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint payments_provider_check check (
    (
      (provider)::text = any (
        (
          array[
            'MOMO'::character varying,
            'VNPAY'::character varying,
            'NONE'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint payments_status_check check (
    (
      (status)::text = any (
        (
          array[
            'UNPAID'::character varying,
            'PAID'::character varying,
            'FAILED'::character varying,
            'REFUNDED'::character varying,
            'PENDING'::character varying,
            'PROCESSING'::character varying,
            'PARTIAL_REFUND'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_payments_order on public.payments using btree (order_id) TABLESPACE pg_default;

create index IF not exists idx_payments_status on public.payments using btree (status) TABLESPACE pg_default;

create index IF not exists idx_payments_transaction_id on public.payments using btree (transaction_id) TABLESPACE pg_default;

create table public.shipments (
  id bigint generated by default as identity not null,
  carrier character varying(100) null,
  delivered_at timestamp with time zone null,
  shipped_at timestamp with time zone null,
  status character varying(255) not null,
  order_id uuid not null,
  constraint shipments_pkey primary key (id),
  constraint ukhrhy2yghr8dampg1jtecuekvp unique (order_id),
  constraint fkrnt4wht95lxxplspltrg9681s foreign KEY (order_id) references orders (id),
  constraint shipments_status_check check (
    (
      (status)::text = any (
        (
          array[
            'PENDING'::character varying,
            'IN_TRANSIT'::character varying,
            'DELIVERED'::character varying,
            'RETURNED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table public.reviews (
  id bigint generated by default as identity not null,
  comment text null,
  created_at timestamp with time zone not null,
  rating integer not null,
  status character varying(255) not null,
  order_item_id bigint not null,
  product_id uuid not null,
  user_id uuid not null,
  constraint reviews_pkey primary key (id),
  constraint uk96f6ovfc9wn4579incehx4gra unique (order_item_id),
  constraint fkcgy7qjc1r99dp117y9en6lxye foreign KEY (user_id) references users (id),
  constraint fkpl51cejpw4gy5swfar8br9ngi foreign KEY (product_id) references products (id),
  constraint fk2x2x74lnliqmt91bc1w95ll8n foreign KEY (order_item_id) references order_items (id),
  constraint reviews_rating_check check (
    (
      (rating >= 1)
      and (rating <= 5)
    )
  ),
  constraint reviews_status_check check (
    (
      (status)::text = any (
        (
          array[
            'PENDING'::character varying,
            'APPROVED'::character varying,
            'REJECTED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table public.support_tickets (
  id uuid not null,
  content text not null,
  created_at timestamp with time zone not null,
  status character varying(20) not null,
  subject character varying(100) not null,
  title character varying(255) not null,
  user_id uuid not null,
  constraint support_tickets_pkey primary key (id),
  constraint fk4reg1h2465c00bg6dmqlv7ujv foreign KEY (user_id) references users (id),
  constraint support_tickets_status_check check (
    (
      (status)::text = any (
        (
          array[
            'OPEN'::character varying,
            'IN_PROGRESS'::character varying,
            'RESOLVED'::character varying,
            'CLOSED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table public.warranty_requests (
  id bigint generated by default as identity not null,
  description text null,
  issue_type character varying(100) not null,
  requested_at timestamp with time zone not null,
  resolved_at timestamp with time zone null,
  status character varying(50) not null,
  order_item_id bigint not null,
  constraint warranty_requests_pkey primary key (id),
  constraint fkqr2fimrurcm4ex3c5e246adja foreign KEY (order_item_id) references order_items (id),
  constraint warranty_requests_status_check check (
    (
      (status)::text = any (
        (
          array[
            'SUBMITTED'::character varying,
            'ACCEPTED'::character varying,
            'REJECTED'::character varying,
            'REPAIRED'::character varying,
            'REPLACED'::character varying,
            'RETURNED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_warranty_order_item on public.warranty_requests using btree (order_item_id) TABLESPACE pg_default;

create index IF not exists idx_warranty_status on public.warranty_requests using btree (status) TABLESPACE pg_default;

create index IF not exists idx_warranty_requested_at on public.warranty_requests using btree (requested_at) TABLESPACE pg_default;

create table public.articles (
  id uuid not null,
  active boolean not null,
  content text not null,
  published_at timestamp with time zone not null,
  slug character varying(255) not null,
  summary text null,
  title character varying(255) not null,
  admin_id uuid not null,
  constraint articles_pkey primary key (id),
  constraint uksn7al9fwhgtf98rvn8nxhjt4f unique (slug),
  constraint fklo27xbtyrh55maq9a3ov3s45a foreign KEY (admin_id) references users (id)
) TABLESPACE pg_default;

create table public.ai_vector_store (
  id uuid not null default extensions.uuid_generate_v4 (),
  content text null,
  metadata json null,
  embedding public.vector null,
  constraint ai_vector_store_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists ai_vector_store_index on public.ai_vector_store using hnsw (embedding vector_cosine_ops) TABLESPACE pg_default;