# Sao chép file này thành application-secret.properties và điền giá trị thật
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require
spring.datasource.username=postgres.ykgnutyoljducellogkm
spring.datasource.password=your-database-password-here

app.bank.bin=970436
app.bank.account-number=your-account-number
app.bank.account-name=YOUR NAME
app.bank.bank-name=Vietcombank
app.bank.qr-template=compact2
